### PR TITLE
Some general fixes and some fixes for platform

### PR DESCRIPTION
**Pull request by 0xFireball**
This PR contains a bunch of fixes, including:

- Use .NET's built-in features for getting things like the directory separator character.
- Fix the bug that made the `New Project` dialog not work (https://github.com/VitalElement/AvalonStudio/pull/211/commits/2e43af2c98c48ce93cd66b827573e8d1ed2c1da0)
- Use culture aware comparison in Platform
- Rename `OS X` to `macOS`, as that is what it will be called moving forward
- Use a subdir of the user profile (`~\AvalonStudio`) as the default project path on all platforms (use a built-in .NET feature rather than hardcoding the path). This is also better than using `C:\AvalonStudio` on Windows as not all users have access to that directory. It would now work the same way as other platforms on Windows.
- Fix some odd code formatting

### CODE REVIEW

**Comment by 0xFireball** [comment]
https://www.jimrich.sk/2015/01/18/environment-specialfolder-on-windows-linux-and-os-x/

**Comment by 0xFireball** [comment]
I changed the platform name back as it may break some paths in `NativeBinaries`. The variable name has been updated to reflect the name change of the OS.

**Comment by 0xFireball** [comment]
The new project dialog did not show because a `NotImplementedException` had been thrown when trying to discover the C# project type: https://github.com/VitalElement/AvalonStudio/blob/0d1ecdd7f8cee6710678d25eb48e64a3a3ef6bd8/AvalonStudio/AvalonStudio.Languages.CSharp/CSharpLanguageService.cs#L42-L48

This has been fixed; now there's a dummy C# project that has a type, but throws a `NotImplementedException` when you actually try to create the project. This fixed the bug that caused the new solution menu not to open.

**Comment by danwalmsley** [comment]
@0xFireball you need to merge to master ;)

**Pull request merged**
