### PR TITLE
Typescript support (preview quality)

### PR DESCRIPTION
**Pull request by 0xFireball**
This pull request adds TypeScript support to AvalonStudio.

Status:
- [x] AvalonStudio Extension library
- [x] Project Templates
  - [x] Template in AvalonStudio project creation
  - [x] Template classes
- [x] Build Toolchains
  - [x] TypeScript compilation
- [x] IntelliSense (in progress)
  - [x] TypeScript compiler access https://github.com/0xFireball/NTypeScript
  - [x] Code completion provider
  - [x] Bindings toTypeScript compiler API (partial; usable)
  - [x] Editor IntelliSense (in progress)
  - [x] Editor Inspections/Linting
- [x] Code analysis
  - [x] Analyze parse tree
  - [x] Walk through tree and provide syntax highlighting

### CODE REVIEW

**Comment by 0xFireball** [comment]
**UPDATE**: 
- The TypeScript plugin now fully supports standard compilation. It uses the same method as VSCode to compile all the files in the project directory.
**Issues**:
- I would like to be able to exclude the `.js` and `.js.map` files (output from TypeScript compiler) from the project tree.

**Comment by danwalmsley** [comment]
There is a excludefilter list of paths, that can do this, might have to be extended to work with wildcards. Can you get it to compile into a build directory? Or does that not make sense in this case?

**Comment by danwalmsley** [comment]
@0xFireball here is some information on implementing typescript language service...

http://dickvdbrink.github.io/typescript/2014/10/04/TypeScript-language-service.html
https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API

This will be the best way to do completion and get the warnings / errors

**Comment by 0xFireball** [comment]
Code completion's now working! I'm working on the bridge here:
https://github.com/0xFireball/TSBridge

**Comment by 0xFireball** [comment]
looks like IridiumJS is missing the x86, x64 platforms

**Comment by 0xFireball** [comment]
i accidentally committed on a detatched HEAD. this should be fixed now.

**Comment by 0xFireball** [comment]
builds are passing 👍

**Comment by danwalmsley** [comment]
@0xFireball I think the travis one is failing, because it might not be copying one of the dependencies to 
avalonbuild project, (postbuild action ... plugin) if the command has false after it, then it doesn't copy.

Not sure if you dll has something embedded or it needs any dependencies, if it does, you need to call plugin command on these too.

**Comment by danwalmsley** [comment]
@0xFireball I will try to resolve the conflicts for you if I get chance tomorrow.

**Comment by 0xFireball** [comment]
All right, thanks

**Comment by 0xFireball** [comment]
https://ci.appveyor.com/project/danwalmsley/avalonstudio/build/1.0.1587#L903
Intellisense API looks to be broken? @danwalmsley

**Comment by 0xFireball** [comment]
@danwalmsley core support for TypeScript is almost ready!

**Comment by 0xFireball** [comment]
Current status of TypeScript support:
- Language node highlighting is working, but we want to be able to highlight even more
- Intellisense is working, but not perfectly. Unfortunately this is controlled entirely by the TypeScript language service
- Build is working correctly, it uses the `tsc` compiler that the user can install separately
- Run is working; the debugger runs the generated JS source in an IridiumJS engine.

**Comment by 0xFireball** [comment]
@danwalmsley so what else should be done before we merge this preview version of typescript support into `master`?

**Comment by danwalmsley** [comment]
@0xFireball thanks for this amazing effort!

**Pull request merged**
