### PR TITLE
Move to SharpGenTools.Sdk

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Move CorApi.Portable to SharpGenTools.Sdk and off the outdated build of SharpGen it was using. Still pre-generate the mappings since we want to make sure we can build off-Windows. 

Depends on https://github.com/VitalElement/AvalonStudio.DebuggerLibs/pull/1

### CODE REVIEW

**Comment by danwalmsley** [comment]
@jkoritzinsky did you see my comments on gitter?

Even removing the hiding dispose and Shadow properties I wasnt able to get this to work, let me know if your around anytime soon I can help debug the issue.

**Comment by jkoritzinsky** [comment]
I'm working on adding unit tests for the runtime support library (SharpGen.Runtime) and I think I might have found this bug. I'll keep you updated. I don't think it's a bug in the code in this PR, just in SharpGen.Runtime.

**Comment by jkoritzinsky** [comment]
I found the bug. I'll update this PR once I release a version of SharpGen.Runtime with the fix.

**Comment by danwalmsley** [comment]
@jkoritzinsky ok iv updated and added a submodule where I can add SharpGen.Runtime dll as a DLL reference for debugging. It gets to SetManagedHandler and returns invalid parameters.

**Comment by jkoritzinsky** [comment]
@danwalmsley The commit I just pushed has the bugfixes in SharpGen.Runtime and SharpGen.Runtime.COM. The .NET debugger is working now with the SharpGen tools-based code.

**Pull request merged**
